### ISSUE TITLE
Power Off/Reset button on UI

### ISSUE THREAD

**Issue by jennyb** [tomjon/piSpecMon#20]
I'm just about to move the PSM from one location to another. Ideally, when I unplug the power, the UPS will nicely power down the Pi, but I worry that the UPS is not reliable.

Can we have both a power off and a reboot button on the UI ( in the admin/setup area ). The power off does a shutdown -h now, the reboot does a shutdown -r now.

**Comment by tomjon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#20 Power Off/Reset button on UI](https://trello.com/c/W9OGfVJH/33-20-power-off-reset-button-on-ui)
