### ISSUE TITLE
Email on power-up

### ISSUE THREAD

**Issue by jennyb** [tomjon/piSpecMon#21]
When plugging the PSM into a new network, it is often given an IP by DHCP. This can be difficult to find on some networks without nmap/portscan, and this can be frowned on by sysAdmins. When the PSM is powered up and gets an IP address, it should send this IP address and its name ( eg PSM11 ) to an email address : remote.systems@ofcom.org.uk. The PSM might also have a 3G connection that gets an email address, we could also send that as it becomes available.

**Comment by tomjon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#21 Email on power-up](https://trello.com/c/PiPv9lf0/32-21-email-on-power-up)
