### ISSUE TITLE
Number of decimal places displayed hovering over graph ( too many ) 

### ISSUE THREAD

**Issue by jennyb** [tomjon/piSpecMon#22]
![psm_decimal_paces](https://cloud.githubusercontent.com/assets/289595/18250756/00ddaf76-737d-11e6-9b28-05e643ade57c.png)

**Comment by tomjon** [comment]
Since strengths are read and stored as integers, something bizarre is going on somewhere!

**Comment by tomjon** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SnWyXvfW&#x2F;31-22-number-of-decimal-places-displayed-hovering-over-graph-too-many"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #22 Number of decimal places displayed hovering over graph ( too many )</a>

**Comment by tomjon** [comment]
Can not reproduce so far - could be an IE (Edge)  only bug?
