### ISSUE TITLE
Scanning with a frequency step of 12.5KHz

### ISSUE THREAD

**Issue by jennyb** [tomjon/piSpecMon#56]
I tried a sweep of 170MHz to 174MHz with a channel size of 0.0125MHz and the step size seemed to remain at 0.1MHz even though the dialog box was correct. We also need more decimal places on the green scanning status readout. 

Update : watching the radio, it is scanning with 12.5KHz steps, it does not look like this on the UI because of too few decimal places.

**Comment by tomjon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#56](https://trello.com/c/CYOnSXOn/75-56)

**Comment by tomjon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#56](https://trello.com/c/CYOnSXOn/75-56)
